[package]
name = "ps5-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core
log = "0.4"
env_logger = "0.10"
crossbeam = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.4"

# Interface
egui = "0.27"
eframe = "0.27"
egui_extras = "0.27"

# Gamepad (suporte a DualShock, DualSense, Xbox, etc)
gilrs = "0.10"

# Android
[target.'cfg(target_os="android")'.dependencies]
jni = "0.21"
android_logger = "0.13"

[profile.release]
lto = true
strip = true
opt-level = 3

[features]
default = ["desktop"]
desktop = []
android = ["jni", "android_logger"]
